#!/usr/bin/env node
'use strict';

/**
 * Entrance file, use this to run the server:
 * node ranvier [options]
 *
 * Options:
 *   -v Verbose loggin
 *   --port Port to listen on
 *   --locale Locale to act as the default
 *   --save Minutes between autosave
 *   --respawn Minutes between respawn
 */

const Ranvier = require('./index.js')
const app = new Ranvier()
app.init()
